import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import {
  Sidebar,
  SidebarFooter,
  SidebarHeader,
  SidebarMenuButton,
} from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/toaster";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <Sidebar>
            <SidebarHeader>
              <a href="/">Home</a>
            </SidebarHeader>
            <SidebarMenuButton asChild>
              <a href="/about-me">About me!</a>
            </SidebarMenuButton>
            <SidebarMenuButton asChild>
              <a href="/drugpage">Drug Abuse Informations</a>
            </SidebarMenuButton>
            <SidebarMenuButton asChild>
              <a href="/quiz">Quiz- Drug Knowledge Test</a>
            </SidebarMenuButton>
          
            
            <SidebarFooter>
              <div className="footer-dropdown">
                <span className="dropdown-toggle">Resources ▼</span>
                <ul className="dropdown-menu">
                  <li>
                    <a href="https://www.addictiongroup.org/drugs/" target="_blank">
                      NIDA - Drug Abuse
                    </a>
                  </li>
                  <li>
                    <a
                      href="https://www.webmd.com/a-to-z-guides/drug-side-effects-explained"
                      target="_blank"
                    >
                      WHO - Substance Use
                    </a>
                  </li>
                  <li>
                    <a href="https://www.bing.com/search?q=how+to+quit+drugs&FORM=AWRE" target="_blank">
                      Recovery Resources
                    </a>
                  </li>
                </ul>
              </div>
            </SidebarFooter>
          </Sidebar>

          <main>
            <SidebarTrigger />
            {children}
            <Toaster />
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
